### ISSUE TITLE
Header is not responsive

### ISSUE THREAD

**Issue by aditya9940** [arijeet-mukherjee/app-home-frontend#27]
<img width="1164" alt="Screenshot 2024-06-07 at 12 38 07 AM" src="https://github.com/arijeet-mukherjee/app-home-frontend/assets/43637601/8f8f5b73-a854-470f-8dfb-92c64a2025fe">

**Comment by Bibhuti05** [comment]
https://github.com/arijeet-mukherjee/app-home-frontend/pull/30/files

**Comment by aditya9940** [comment]
fixed
