### ISSUE TITLE
Header Humberger responsive issue

### ISSUE THREAD

**Issue by arijeet-mukherjee** [arijeet-mukherjee/app-home-frontend#7]
<img width="790" alt="image" src="https://github.com/arijeet-mukherjee/app-home-frontend/assets/39984190/0d12bc12-5e21-4fe0-bf1f-3c0e04224ce8">

**Comment by Bibhuti05** [comment]
Fix to this has been added to scratch/fix/siteHeader Branch

**Comment by aditya9940** [comment]
fixed
